export enum ShippingServiceCode {
  // Ground
  GROUND = 'GROUND',

  // Express / Next Day
  NEXT_DAY_AIR = 'NEXT_DAY_AIR',
  NEXT_DAY_AIR_SAVER = 'NEXT_DAY_AIR_SAVER',
  NEXT_DAY_AIR_EARLY = 'NEXT_DAY_AIR_EARLY',

  // 2-Day
  SECOND_DAY_AIR = 'SECOND_DAY_AIR',
  SECOND_DAY_AIR_AM = 'SECOND_DAY_AIR_AM',

  // 3-Day
  THREE_DAY_SELECT = 'THREE_DAY_SELECT',

  // Heavy / Freight
  HEAVY_GOODS = 'HEAVY_GOODS',

  // International
  WORLDWIDE_EXPRESS = 'WORLDWIDE_EXPRESS',
  WORLDWIDE_EXPRESS_PLUS = 'WORLDWIDE_EXPRESS_PLUS',
  WORLDWIDE_EXPEDITED = 'WORLDWIDE_EXPEDITED',
  WORLDWIDE_SAVER = 'WORLDWIDE_SAVER',
  STANDARD_INTERNATIONAL = 'STANDARD_INTERNATIONAL',
  WORLDWIDE_EXPRESS_FREIGHT = 'WORLDWIDE_EXPRESS_FREIGHT',
  WORLDWIDE_EXPRESS_FREIGHT_MIDDAY = 'WORLDWIDE_EXPRESS_FREIGHT_MIDDAY',
}
